### ISSUE TITLE
README

### ISSUE THREAD

**Issue by kenju254** [winklers/information_lgbt#2]
Hi @winklers  is there an information guide about what is needed to contribute to your projects ?

**Comment by winklers** [comment]
Thanks @kenju254 . I added an issues section to the `README` in my [winklers/aid_data_lgbt](https://github.com/winklers/aid_data_lgbt). It involves writing code to standardize geo names and match based on those names. Take a look if you get a chance and let me know if you have ideas. 

Also, fyi: no update on the big data twitter project yet. Hopefully I can work on that closer to September.

**Comment by kenju254** [comment]
@winklers heya just popped in here and noticed that a lot has happened and gone into this :) .. I will try to get familiar with and see what is going on.. Also great work on the documentation ..
